### ISSUE TITLE
Question about Random Forest

### ISSUE THREAD

**Issue by shaowei-su** [endymecy/spark-ml-source-analysis#2]
you've mentioned in this section https://github.com/endymecy/spark-ml-source-analysis/blob/master/%E5%88%86%E7%B1%BB%E5%92%8C%E5%9B%9E%E5%BD%92/%E7%BB%84%E5%90%88%E6%A0%91/%E9%9A%8F%E6%9C%BA%E6%A3%AE%E6%9E%97/random-forests.md that there seem to be two scoring methods: predictBySumming and predictByVoting.

But in ml package, I only find 

`  override protected def predictRaw(features: Vector): Vector = {
    // TODO: When we add a generic Bagging class, handle transform there: SPARK-7128
    // Classifies using majority votes.
    // Ignore the tree weights since all are 1.0 for now.
    val votes = Array.fill[Double](numClasses)(0.0)
    _trees.view.foreach { tree =>
      val classCounts: Array[Double] = tree.rootNode.predictImpl(features).impurityStats.stats
      val total = classCounts.sum
      if (total != 0) {
        var i = 0
        while (i < numClasses) {
          votes(i) += classCounts(i) / total
          i += 1
        }
      }
    }
    Vectors.dense(votes)
  }`

Does this means that ml random forest only support voting scoring?

Thank you in advance.

**Comment by endymecy** [comment]
predictBySumming and predictByVoting in class org.apache.spark.mllib.tree.model.TreeEnsembleModel
