### ISSUE TITLE
NaiveBayesMode的bernoulliCalculation是怎么计算的？

### ISSUE THREAD

**Issue by JokerDu** [endymecy/spark-ml-source-analysis#3]
[分类与回归-朴素贝叶斯](https://github.com/endymecy/spark-ml-source-analysis/blob/master/%E5%88%86%E7%B1%BB%E5%92%8C%E5%9B%9E%E5%BD%92/%E6%9C%B4%E7%B4%A0%E8%B4%9D%E5%8F%B6%E6%96%AF/nb.md)，看到您分析的时候好像没有提到公式是怎么计算的。
Spark的代码在[bernoulliCalculation](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/classification/NaiveBayes.scala#L315)
看了好久，先感谢啦

**Comment by endymecy** [comment]
我又做了一些说明，你可以去看看。
